
name: Push Docker Hub

on:
  push:
    branches: [ master, main ]
  schedule:
    # Every sunday at 0:00
    - cron:  '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Mainline Debian Version
      uses: docker/build-push-action@v2
      with:
        context: ./v3.1
        platforms: linux/amd64
        push: true
        tags: |
          jawg/mapnik3:latest
          jawg/mapnik3:3.1
          jawg/mapnik3:3.1-bullseye